language: node_js
node_js:
    - "4"
    - "5"
    - "6"

addons:
  code_climate:
    repo_token: bf476893eaa8ce6ceffc82a184486b4ac0100fc010437651e1147cdc76b9e9da

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info